name: Build CloudStream extension

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10.2'

      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.10.2

      - name: Build Extensions
        run: ./gradlew samehadaku:make
        
      - name: Generate Plugins JSON
        run: ./gradlew makePluginsJson

      - name: Check Generated Plugins JSON
        run: |
          echo "=== GENERATED PLUGINS.JSON ==="
          cat build/plugins.json

      - name: Prepare Repository
        run: |
          mkdir -p publish

          echo "=== Mencari file CS3 ==="
          find . -name "*.cs3" -type f

          echo "=== Menyalin plugin ==="
          cp samehadaku/build/*.cs3 publish/

          echo "=== Menyalin plugins.json hasil Gradle ==="
          cp build/plugins.json publish/

          echo "=== Membuat repo.json ==="
          cat > publish/repo.json <<EOF
          {
            "name": "Naufal Namikaze CloudStream",
            "description": "My CloudStream extensions",
            "manifestVersion": 1,
            "pluginLists": [
              "https://raw.githubusercontent.com/${{ github.repository }}/builds/plugins.json"
            ]
          }
          EOF

          echo "=== HASIL PUBLISH ==="
          echo
          cat publish/plugins.json
          echo
          cat publish/repo.json
          echo
          ls -lah publish
