name: Build CloudStream extension

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10.2'

      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.10.2

      - name: Build Extensions
        run: ./gradlew make makePluginsJson

      - name: Prepare Repository
        run: |
          mkdir -p publish

          cp samehadaku/build/*.cs3 publish/

          cp plugins.json publish/

          cat > publish/repo.json <<'EOF'
          {
            "name": "Naufal Namikaze CloudStream",
            "description": "My CloudStream extensions",
            "manifestVersion": 1,
            "pluginLists": [
              "https://raw.githubusercontent.com/${{ github.repository }}/builds/plugins.json"
            ]
          }
          EOF

          echo "=== PUBLISH FILES ==="
          find publish -type f -maxdepth 1 -print

      - name: Publish builds branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout --orphan builds
          git rm -rf . 2>/dev/null || true

          cp -r publish/* .

          git add .
          git commit -m "Update CloudStream extensions"
          git push --force origin builds
